
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Bios-Marcel/cordless
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go vet ./...
      - run: go test -race -coverprofile=profile.out -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash) -f profile.out
      - run: go build

      - store_artifacts:
          path: /go/src/github.com/Bios-Marcel/cordless/cordless
          destination: cordless