
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/Bios-Marcel/cordless
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test ./...
      - run: go build

      - store_artifacts:
          path: /go/src/github.com/Bios-Marcel/cordless/cordless
          destination: cordless
  
  snap:
    docker:
      - image: cibuilds/snapcraft:stable
    
    steps:
      - checkout
      - run:
          name: "Build Snap"
          command: snapcraft

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - snap