name: cordless
version: git
summary: Third party discord client
description: |
  A third party discord client for your terminal.

confinement: strict
grade: stable

base: core18

parts:
  cordless:
    plugin: go
    go-importpath: github.com/Bios-Marcel/cordless
    source: .
    source-type: git
    stage-packages:
      - xclip

apps:
  cordless:
    command: bin/cordless
    plugs: [x11, network-bind]
    environment:
      XDG_CONFIG_DIR: $SNAP_USER_DATA/