name: Build
on: push
jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Go 1.12 build ubuntu
        uses: actions/setup-go@v1
        with:
          version: 1.12

      - name: Checkout master
        uses: actions/checkout@master

      - name: Run tests and build
        env:
          GO111MODULE: on
        run: go test ./... && go build .
#  windows:
#    name: Windows build
#    runs-on: windows-latest
#  macos:
#    name: MacOS build
#    runs-on: macOS-latest
